steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/gpt-note-app", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/gpt-note-app"]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "gpt-note-app"
      - "--image=gcr.io/$PROJECT_ID/gpt-note-app"
      - "--platform=managed"
      - "--region=us-central1"
      - "--allow-unauthenticated"
